### ISSUE TITLE
Please add a documentation.

### ISSUE THREAD

**Issue by PhiApp** [tuesd4y/node-webuntis#1]
Please add a documentation. I really, really would like it, to use your API because it is written in NodeJS. I am going to make a little application for my school and I need an API for webuntis. 

If you have time and you want to help me, so please contact me.

**Comment by tuesd4y** [comment]
whoa, thanks for the quick feedback, I'm currently a little busy at school myself but I'll see what I can do ;)

What school are you going to, if i may ask?

**Comment by PhiApp** [comment]
Ye, I found your API through luckily. I am going to school in lower austria, in a IT-HTL.

**Comment by tuesd4y** [comment]
22bedb4 -> here you go ;)

**Comment by PhiApp** [comment]
Wow, nice thank you very much! Where can I change the webuntis server address?
